function imatlab_export_plotly()

  setenv('IMATLAB_EXPORT_FIG', func2str(@(h) eval([ ...
   'fig2plotly(h, ''filename'', [tempname(''.''), ''.html''], ', ...
                 '''offline'', true, ''open'', false); ', ...
   'close(h);'])));
   
end
